import numpy as np
import pandas as pd
from scipy.optimize import least_squares

from .base import CovarianceEstimator
from ..params import Param
from ..tenor_graph import tenor_to_years


def _softplus(x: np.ndarray) -> np.ndarray:
    return np.logaddexp(0.0, x)


class HJMKernelEstimator(CovarianceEstimator):
    """Gaussian multi-factor HJM (Hull-White / LGM) covariance.

    Replaces the ~n²/2 sample-covariance entries with a smooth PSD matrix
    C = A P Aᵀ generated by k factors, where A[a,i] = σ_i·exp(-λ_i·τ_a), τ is
    each tenor's time-to-maturity in years, and P is the k×k factor correlation
    — only 2k + C(k,2) parameters. Fit by trust-region least squares against the
    sample covariance using an unconstrained reparameterization, so constraints
    (σ>0, ordered λ>0, valid correlation P) hold automatically.

    weighting="uniform" matches covariance levels; "corr" weights by
    1/√(Σ_aa·Σ_bb) to fit the correlation shape instead of the high-variance end.
    """

    PARAMS = [Param("k", int, default=3, min=1, max=6, label="factors (k)")]

    def __init__(self, k: int = 3, weighting: str = "uniform", n_restarts: int = 4):
        self.k = k
        self.weighting = weighting
        self.n_restarts = n_restarts
        self.params_: dict | None = None

    def fit(self, series: pd.DataFrame) -> np.ndarray:
        S   = np.cov(series.values.T)
        tau = np.array([tenor_to_years(c) for c in series.columns])
        n   = len(tau)
        k   = min(self.k, n)

        iu     = np.triu_indices(n)
        target = S[iu]
        if self.weighting == "corr":
            d  = np.sqrt(np.diag(S))
            sw = 1.0 / np.sqrt(np.outer(d, d)[iu])
        else:
            sw = np.ones(len(target))

        tril = np.tril_indices(k, -1)

        def unpack(theta):
            sigma = np.exp(theta[:k])
            lam   = np.cumsum(_softplus(theta[k:2 * k]))  # cumulative -> λ>0 and ordered
            L = np.eye(k)
            L[tril] = theta[2 * k:]
            L /= np.linalg.norm(L, axis=1, keepdims=True)  # unit rows -> P=LLᵀ is a correlation
            return sigma, lam, L @ L.T

        def model(theta):
            sigma, lam, P = unpack(theta)
            A = sigma * np.exp(-np.outer(tau, lam))
            return A @ P @ A.T

        def resid(theta):
            return sw * (model(theta)[iu] - target)

        rng  = np.random.default_rng(0)
        best = None
        for r in range(max(1, self.n_restarts)):
            sol = least_squares(resid, self._init(S, tau, k, rng, jitter=r > 0), method="trf")
            if best is None or sol.cost < best.cost:
                best = sol

        sigma, lam, P = unpack(best.x)
        self.params_ = {"sigma": sigma, "lambda": lam, "rho": P, "k": k}
        return model(best.x)

    def _init(self, S, tau, k, rng, jitter):
        sigma0 = np.sqrt(max(np.diag(S).mean(), 1e-12) / k)
        s0     = np.full(k, np.log(sigma0))
        # decay rates log-spread from slow (whole-curve level) to fast (short end)
        incr   = np.maximum(np.diff(np.geomspace(1 / tau.max(), 1 / tau.min(), k), prepend=0.0), 1e-6)
        l0     = np.log(np.expm1(incr))  # softplus inverse of the per-factor λ increments
        theta0 = np.concatenate([s0, l0, np.zeros(k * (k - 1) // 2)])
        return theta0 + rng.normal(scale=0.5, size=theta0.shape) if jitter else theta0
